<?php 
/*
Plugin Name: WP MailCatcher
Plugin URI: https://github.com/gitaurone/WP_mailcatcher/
Description: This plugin re-routes all WordPress emails to Mailcatcher, which is super handy if you need to inspect outgoing emails from your plugin.
Author: Mohamed Ali Rajab
Version: 1.0.0
Author URI: https://www.aurone.com
*/

namespace Aurone\WP_Plugins\Mailcatcher;

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}


// if it's not Aurone local server, get out of this plugin !
if ( 'aurone' != gethostname() ) {
    return;
}


class Mailcatcher {
    
    /**
    * Send in arguments for mailer.
    *
    * @param array $config Configuration values. These will take presedence over $defaults.
    */
    
    public function __construct(array $config = [])
    {
        // Setup our defaults
        
        $defaults = [
            "from"	   => "local@aurone.dev",
            "fromname" => "Aurone local server",
            "host"     => "127.0.0.1",
            "port"     => "1025",
            "smtpauth" => false
        ];
        
        $config = wp_parse_args($config, $defaults);
        
        // Setup mailer
        
        $this->setupMail($config);
        
    }
    
    /**
    * Setup mailer.
    *
    * @param array $config Parsed configuration values.
    */
    
    private function setupMail(array $config)
    {
        add_action('phpmailer_init', function($phpmailer) use($config) {
            
            extract($config, EXTR_SKIP);
            
            // $phpmailer->From     = $from;
            $phpmailer->FromName = $fromname;
            $phpmailer->Sender   = $phpmailer->From;
            $phpmailer->Host     = $host;
            $phpmailer->Port     = (int) $port;
            $phpmailer->SMTPAuth = (boolean) $smtpauth;
            $phpmailer->isSMTP();
            
        });
    }
    
    /**
    * Send a test email.
    */
    
    public function sendMail()
    {
        add_action('plugins_loaded', function(){
            
            $to 		= "test@aurone.dev";
            $subject 	= "Subject Generated by Mailcatcher";
            $message 	= "Body Generated by Mailcatcher for WordPress";
            
            \wp_mail($to, $subject, $message);
            
        });
    }
    
}



$mailcatcher = new Mailcatcher;

// if you whant to test it, the next line will send a test email on every request
// $mailcatcher->sendMail();
